#!/usr/bin/env node
/**
 * Export training data from the NLU Bot Trainer's localStorage format
 * to a JSON file compatible with the Python training pipeline.
 *
 * Usage (run in browser console, then copy output to file):
 *
 *   // In the NLU Trainer browser tab, open DevTools Console (F12) and paste:
 *   const data = JSON.parse(localStorage.getItem('nlu-bot-trainer-data'));
 *   const exported = {
 *     intents: data.intents.map(i => ({
 *       name: i.name,
 *       description: i.description,
 *       examples: i.examples.map(e => ({ text: e.text, entities: e.entities || [] }))
 *     })),
 *     entities: data.entities.map(e => ({
 *       name: e.name,
 *       description: e.description,
 *       values: e.values
 *     })),
 *     metadata: data.metadata
 *   };
 *   // Download as file
 *   const blob = new Blob([JSON.stringify(exported, null, 2)], {type: 'application/json'});
 *   const url = URL.createObjectURL(blob);
 *   const a = document.createElement('a');
 *   a.href = url; a.download = 'training_data.json'; a.click();
 *   URL.revokeObjectURL(url);
 *   console.log('Exported', exported.intents.reduce((s,i) => s + i.examples.length, 0), 'examples');
 *
 * Or, if you have the default data and just want to generate the file:
 *   node export_from_app.js > training_data.json
 */

// Default training data (mirrors store.ts getDefaultData)
// This lets you generate training_data.json without running the app
const defaultData = {
  intents: [
    {
      name: "greet",
      description: "Customer greets or initiates conversation",
      examples: [
        "hello", "hi there", "good morning", "hey", "hi", "good afternoon",
        "good evening", "howdy", "what's up", "greetings", "hello there",
        "hey there", "hiya", "yo", "sup", "good day", "nice to meet you",
        "pleased to meet you", "morning", "evening", "hey how are you",
        "hello is anyone there", "hi I need some help", "hey good to see you",
        "aloha", "well hello there", "hi again", "hey how's it going",
        "good morning I have a question", "afternoon",
        "hey can someone help me", "hello hello", "oh hi",
        "hey what's going on", "hi I'm new here",
      ],
    },
    {
      name: "goodbye",
      description: "Customer ends conversation",
      examples: [
        "bye", "goodbye", "see you later", "take care", "see you",
        "have a nice day", "catch you later", "talk to you soon", "bye bye",
        "good night", "farewell", "until next time", "I'm leaving now",
        "that's all I needed", "gotta go", "I'm done here",
        "have a great day", "peace out", "later", "ttyl",
        "alright bye then", "I'll be going now", "thanks that's all bye",
        "ok I'm off", "see ya", "signing off now",
        "I have to go now goodbye", "night night", "cheers bye",
        "ok thanks bye", "that was everything I needed goodbye",
        "cya later", "adios", "I'm heading out", "toodles",
      ],
    },
    {
      name: "thank_you",
      description: "Customer expresses gratitude",
      examples: [
        "thank you", "thanks a lot", "appreciate it", "thanks so much",
        "thanks", "much appreciated", "that's very helpful",
        "you've been great", "thank you very much", "great help thanks",
        "wonderful thank you", "thanks for your help",
        "I really appreciate your assistance", "you're awesome thanks",
        "perfect thanks", "cheers mate", "brilliant thank you",
        "that was helpful", "I appreciate that",
        "thank you for the quick response", "amazing service thank you",
        "that solved my issue thanks", "exactly what I needed thanks",
        "you really helped me out", "great job thanks so much",
        "super helpful I appreciate it", "thankful for your patience",
        "that fixed it thank you", "grateful for the assistance",
        "nice one thanks", "splendid work thank you",
        "that was fast thanks", "you made my day thanks",
        "excellent support thank you",
        "I'm satisfied with your help thanks",
      ],
    },
    {
      name: "order_status",
      description: "Customer asks about order status or tracking",
      examples: [
        "where is my order", "track my package",
        "when will my order arrive", "what's the status of my delivery",
        "has my order shipped yet", "I want to know where my package is",
        "can I track my order", "my order hasn't arrived yet",
        "order tracking information", "when is my delivery expected",
        "check order status", "estimated delivery date",
        "give me tracking number", "is my package on the way",
        "my shipment is late", "delivery update please",
        "what's happening with my order", "order still processing",
        "any update on my package", "where's my stuff",
        "how long until my order arrives",
        "I placed an order three days ago where is it",
        "show me the shipping progress",
        "what carrier is delivering my package",
        "has my item been dispatched",
        "I need the tracking link for my order",
        "when was my order shipped",
        "is there a delay with my delivery",
        "my package seems stuck in transit",
        "what is the expected arrival date",
        "I haven't received my order yet",
        "order confirmation says shipped but no update",
        "how do I check my shipping status",
        "tell me when my order will be delivered",
        "I'm waiting for a package from you",
      ],
    },
    {
      name: "return_product",
      description: "Customer wants to return a product",
      examples: [
        "I want to return this item", "how do I return a product",
        "I need to send this back", "what is your return policy",
        "can I get a return label", "I'd like to return my purchase",
        "return this order", "I want to ship this item back to you",
        "initiate a return", "how many days do I have to return",
        "where do I drop off the return", "return shipping address",
        "is return shipping free", "I need a prepaid return label",
        "start the return process",
        "can I exchange this instead of returning",
        "return window for this product",
        "I changed my mind I want to send it back",
        "this doesn't fit I need to return it",
        "how to arrange a return pickup",
        "the item is the wrong size can I return it",
        "I want to swap this for a different one",
        "what are the conditions for returning items",
        "do I need the original packaging to return",
        "print a return slip for me",
        "I'd like an exchange not a return",
        "the product doesn't match the description I want to return it",
        "send me a return authorization number",
        "can I return after 30 days",
        "I received the wrong item I need to return it",
        "schedule a return pickup at my address",
        "where is the nearest drop off point for returns",
        "do you offer free return shipping",
        "I opened the package can I still return",
        "what happens after I ship my return",
      ],
    },
    {
      name: "refund_request",
      description: "Customer requests a refund or money back",
      examples: [
        "I want a refund", "can I get my money back",
        "please process my refund", "I need a refund for this order",
        "when will I receive my refund", "refund status",
        "I was charged incorrectly please refund me",
        "how long does a refund take", "give me my money back",
        "issue a refund please", "I want my money refunded to my card",
        "refund hasn't appeared in my bank account",
        "I'm still waiting for my refund",
        "credit my account back please", "where is my refund",
        "refund to my original payment method",
        "I was overcharged I need money back",
        "process the refund immediately", "how do I get a refund",
        "refund my purchase price",
        "I demand a full refund right now",
        "reimburse me for the defective product",
        "the refund should have arrived by now",
        "can I get store credit instead of a refund",
        "refund the difference in price",
        "I returned the item but no refund yet",
        "partial refund for damaged goods",
        "how many business days for the refund to process",
        "will the refund go back to my credit card",
        "I never received the item I want my money back",
        "the service was terrible I expect a refund",
        "do you have a money back guarantee",
        "I want to be reimbursed for shipping costs",
        "apply the refund to my next purchase",
        "why is my refund only partial",
      ],
    },
    {
      name: "complaint",
      description: "Customer files a complaint about quality or experience",
      examples: [
        "I have a complaint", "this product is defective",
        "I received a damaged item", "the quality is terrible",
        "this is not what I ordered",
        "I'm very disappointed with this purchase",
        "the wrong item was delivered", "product arrived broken",
        "I want to file a complaint",
        "terrible experience with your service",
        "your product quality is awful",
        "this item doesn't work at all", "I am extremely unhappy",
        "this is unacceptable", "worst purchase I've ever made",
        "the package was damaged when it arrived",
        "missing parts in my order",
        "the color is completely different from the photo",
        "very poor quality product", "I am dissatisfied with my order",
        "the stitching is already coming apart",
        "I've had nothing but problems with this product",
        "the item stopped working after one day",
        "this looks nothing like the pictures on your website",
        "there was a scratch on the product out of the box",
        "I'm furious about the poor quality",
        "the food was stale when it arrived",
        "your packaging is horrible everything was crushed",
        "I ordered two but only got one and it was broken",
        "the instructions are missing and the product is faulty",
        "I'm really upset about the service I got",
        "the expiration date had already passed",
        "this is a scam the product is fake",
        "I want to report a quality issue",
        "the screen has dead pixels right out of the box",
      ],
    },
    {
      name: "product_inquiry",
      description: "Customer asks about product details, specs, or availability",
      examples: [
        "do you have this in stock", "what sizes are available",
        "tell me about this product",
        "is this item available in blue", "what are the specifications",
        "how much does this cost",
        "is this compatible with my device",
        "what material is this made of",
        "do you ship internationally",
        "when will this be back in stock",
        "what colors does this come in", "what's the price of this item",
        "is there a warranty", "product dimensions please",
        "does this come with batteries",
        "what's the weight of this product", "is this waterproof",
        "compare this with the pro version",
        "any discounts available on this",
        "tell me the features of this item",
        "how many units are left in stock",
        "what is the battery life on this device",
        "is there a newer model coming out soon",
        "can you tell me about the warranty coverage",
        "does this product come in other colors",
        "what are the system requirements",
        "show me similar products in this category",
        "is this product suitable for kids",
        "do you have a size guide for this item",
        "what is the resolution of this display",
        "how much storage does this come with",
        "is assembly required for this item",
        "can I see customer reviews for this product",
        "what are the available configurations",
        "does this product work with bluetooth",
      ],
    },
    {
      name: "cancel_order",
      description: "Customer wants to cancel an order before delivery",
      examples: [
        "I want to cancel my order", "please cancel this order",
        "can I cancel my purchase", "cancel order number",
        "I changed my mind I want to cancel",
        "how do I cancel an order", "stop my order from shipping",
        "I don't want this anymore please cancel",
        "cancel my recent purchase", "is it too late to cancel",
        "void my order", "I placed the wrong order please cancel",
        "cancel before it ships", "I need to cancel right away",
        "revoke my order",
        "I accidentally ordered this please cancel it",
        "withdrawal my order", "don't ship my order cancel it",
        "I no longer need this cancel the order",
        "cancellation request", "undo my last order please",
        "I decided not to buy this anymore cancel it",
        "can I still cancel if it hasn't shipped",
        "please stop processing my order",
        "I ordered by mistake please cancel the order",
        "remove my order from the system",
        "halt the shipment and cancel",
        "I found it cheaper elsewhere please cancel",
        "cancel all pending orders on my account",
        "I want to cancel and reorder with a different address",
        "abort this purchase", "is there a cancellation fee",
        "I need to cancel within the cancellation window",
        "scratch that order I don't want it",
        "please void my recent transaction",
      ],
    },
    {
      name: "payment_issue",
      description: "Customer has payment, billing, or transaction problems",
      examples: [
        "my payment failed", "I was double charged",
        "payment not going through",
        "card declined when trying to pay",
        "billing issue with my account",
        "I see an unauthorized charge",
        "what payment methods do you accept",
        "can I pay with PayPal", "my transaction is pending",
        "update my payment information",
        "credit card not working on your site",
        "charged twice for the same order", "payment declined error",
        "why was I charged extra",
        "incorrect amount on my credit card statement",
        "change my billing address",
        "payment confirmation not received",
        "do you accept Apple Pay", "invoice for my order",
        "my coupon code isn't working at checkout",
        "the promo code gives an error at payment",
        "I got charged but the order didn't go through",
        "my bank says the transaction was blocked",
        "can I split the payment between two cards",
        "do you offer installment payment plans",
        "the checkout page keeps crashing when I try to pay",
        "I need a receipt for tax purposes",
        "there's a pending charge that shouldn't be there",
        "can I change the card on file for my subscription",
        "the total at checkout doesn't match the listed price",
        "I was charged sales tax but I'm tax exempt",
        "my gift card balance isn't showing at checkout",
        "payment security verification keeps failing",
        "do you accept cryptocurrency as payment",
        "I need to update the expiry date on my saved card",
      ],
    },
    {
      name: "account_help",
      description: "Customer needs help with login, password, or account settings",
      examples: [
        "I can't log in to my account", "reset my password",
        "how do I change my email address", "I forgot my password",
        "update my account details", "delete my account",
        "I want to change my shipping address on my profile",
        "how do I create an account",
        "account settings page not loading", "my account is locked",
        "sign up for a new account",
        "verification email not received", "change my username",
        "two factor authentication setup",
        "unsubscribe from emails",
        "my login credentials don't work",
        "how to update my phone number on profile",
        "deactivate my account temporarily",
        "password reset link expired",
        "manage my notification preferences",
        "I keep getting logged out automatically",
        "how do I merge two accounts",
        "my account was hacked what do I do",
        "I want to change the name on my account",
        "enable two step verification for security",
        "the sign up page won't load",
        "how do I view my order history in my account",
        "I never got the verification code",
        "can I have multiple accounts with the same email",
        "my profile picture won't upload",
        "I want to close my account permanently",
        "change the language settings on my account",
        "I can't remember my username or email",
        "link my social media account to my profile",
        "how do I download my account data",
      ],
    },
    {
      name: "speak_to_human",
      description: "Customer wants to escalate to a live agent",
      examples: [
        "I want to speak to a human", "connect me to an agent",
        "let me talk to a real person",
        "transfer me to customer support",
        "I need a human representative",
        "can I speak with a manager", "get me a live agent",
        "I don't want to talk to a bot",
        "put me through to someone",
        "I want real support not automated",
        "escalate this to a supervisor",
        "is there a human I can chat with",
        "this bot isn't helping connect me to staff",
        "I need to speak to a person not a machine",
        "live chat with a representative", "operator please",
        "I want to call your support team",
        "redirect me to human support",
        "hand me over to an actual person",
        "enough with the bot let me talk to someone",
        "can you transfer me to a live representative",
        "I'd rather speak with a real agent",
        "your automated system isn't resolving my issue",
        "give me a phone number to reach a person",
        "I insist on talking to a real human being",
        "please forward my case to a senior agent",
        "is there a way to email a real person",
        "the chatbot can't help me I need a human",
        "I've been going in circles connect me to staff",
        "when is your live support available",
        "I need someone who can actually fix this problem",
        "are your human agents available right now",
        "route me to the complaints department",
        "stop giving me automated responses get me a person",
        "I want to file a formal complaint with a manager",
      ],
    },
  ],
  entities: [
    { name: "product", description: "Product names or categories", values: ["laptop", "phone", "tablet", "headphones", "charger", "keyboard", "mouse", "monitor", "camera", "speaker"] },
    { name: "color", description: "Product color options", values: ["red", "blue", "black", "white", "green", "silver", "gold", "pink"] },
    { name: "size", description: "Size options", values: ["small", "medium", "large", "extra large", "XS", "XL"] },
  ],
  metadata: {
    trainedAt: null,
    totalExamples: 420,
    version: "1.0.0",
  },
};

// Format for the Python training pipeline
const exported = {
  intents: defaultData.intents.map((i) => ({
    name: i.name,
    description: i.description,
    examples: i.examples.map((text) => ({ text, entities: [] })),
  })),
  entities: defaultData.entities,
  metadata: defaultData.metadata,
};

console.log(JSON.stringify(exported, null, 2));
